api_key:
    open_router: ENC[AES256_GCM,data:+Z0OFQ5NA9O74ECgP5WTgd0nnVx5ZOp9+B3/Yz0T8Enzi5U3qIL9OF3/bCtfOntq4PsTKkCE8mSZEM+i7KKmy5bFPmsocIJYCw==,iv:043FXeyFXdb+4yQmf4rG6tip/z+xtB5bimjbV5x5aPE=,tag:wEBSjMTuqCZXxAdSbvgfoA==,type:str]
    openai: ENC[AES256_GCM,data:7cPY6cCyd8cK9VcyO6Ci9vqA+z24HduDybSFj9Nb2uE+UJ/TL0Vl5W+CFCOgHlhkkcIkVXcGdMj1JaUz6kOE9UaYPSPpO4n/OxsxUoP9KDw18UsFVlcOW/0lSJaa2cz7WT81rH1M5FnzE7YjJ7+pYMCOufEoZMY1yVbuQEGYkqHlEqwjVA3f13juMuaDgLBvwjXRE+/uvlb0UF0Iiktn1tQMwbY=,iv:3BnYbSbwiOLailLRJQWc8nOJm1DOydvoZGY2D1xo9V8=,tag:YfVGc5aAuwvUgEalB0rnTg==,type:str]
    tavily: ENC[AES256_GCM,data:M/6I2oWpBevQ6oWBuWjB5+BOgtSnvCHLOjohGK+tda4K5nzA7yCBKz0=,iv:gGzyQlp87gm5Bz2b0LSjwzWE2e7/p4b1IYlQGJC+z60=,tag:mFg+MKuONL3SYRI8buU9VA==,type:str]
container_registry:
    gitlab:
        username: ENC[AES256_GCM,data:hNlncEKezSRAvQkZo3yvp1vV6Ym24Oiijojf,iv:YaDuzFC1tEv8ZgzDnM39dyjCuYQ8RtpEYpefLFF+mcc=,tag:Hx2h/aFzR30p/JN8erjJnQ==,type:str]
        token: ENC[AES256_GCM,data:zomtF/lG9Mh4mpOyRRxJfWMYc6zJsZpIzA==,iv:WSypFouHyE1sv0LpCd6pCAMoNxIajAKtBmyzetZu7cE=,tag:o96JqeJdA1bBRwxHVP0HDw==,type:str]
wireguard:
    wg0:
        my_private_key: ENC[AES256_GCM,data:e3HObsxcvIRvlNPWWCjRODuw2fEICwZtjGK1rE5L/uQRBjm48UvVpXswPCc=,iv:k768/eAkSxPK59qqH5KzshpjnITGJJ5W/wqUaA8NEYI=,tag:WUQPkQLS//WJHkjJfkK2pQ==,type:str]
        peer_psk: ENC[AES256_GCM,data:tHmzJB1juBh3unOhyzmwTooDcPKI3f/aqtg2kluFTqrBEZfi/T0ysJcSLeA=,iv:y1GooF2wSNUGNERa2HDYZe+vjtNKHxtu/sT6+SbykDo=,tag:aw4KQRlbBjD8o/YROVl+Og==,type:str]
backups:
    restic:
        password: ENC[AES256_GCM,data:xQTHMMIXiJ9FpEL4XToZmhMojOOx3AmBWJUj9KS3epiTbRTFZJO8XNS6zyY=,iv:DTQtZNFyPeCa7VQCryizkUMra+hw7xDw3aLE3iW0oQE=,tag:ugub4eoyhL4v8XwekAkHPg==,type:str]
sops:
    age:
        - recipient: age1n93u835nu8nxfetappazpl7ns4h3ys2ehzy624rzs2gp887zff9q96v7e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVlJHL1NrVmV0QjhiV3Fh
            MC9vMGJHbjlreFhsRGRXL1dXWTRGbXRxOVRBCmRTTkFsR3ZWeDQ1TWpSbzZuRmtL
            MHNQSXN5aDZQdlNiWGZKQ0grc1FQMU0KLS0tIEp4eEdxb3VCNUxobmU2MmdLQ3g3
            QVdHWkdrSlp6MEV0NCs1RzMvUzFHakEKMVJu/zHyBnojJSCwJoI5IxIgM3Lg7SOT
            hyWngP7rnHH1a6H8wbC3E1/G/bxTFDyuQpBmx/LEhspoMgCFQLqMsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfkc4sasc5yhfl6u9hxev759eacd8rw6fy9j99utajg7jaxumq6srmr7gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneGw4WVBrRnd2UjBHMkU0
            NlV6Y3VUUmZhMXJwbWFENkFHTGNoNlh1L0RZClNKZEFFY0wrWlo5TWp1c1NoUGdQ
            QUJmSE9YNXhPV3dZcUloZXVYWlEycTgKLS0tIHl0ZDd1czJBMDlOTWg3Nk54VVMv
            ZHd4cmhhY3ZxTUR2TmJqWVVQZ09xQVkK8BUhNXV/7aDyviKAU06CRITFIPojbqzn
            t6D5FYmOPNu7wrJWBygHxWEME8R/4Q9dz6PYPL29eGnIcmnaFnxNlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140mwr39uc7jv0c8qmuxu8cjdv2w2ac0ktfz07huyt5naeph3pf2q503uwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TDZIRmpKNC9ZSllFUW9v
            RWpYU3VSSTY5NDNWYzVqOTFiei84U0hQZUhFCll0VlpqVEJDVDlUVjg3WmxqU2dB
            N3JIMnVBS2JXMmVTSWM0emlEdU9jcTAKLS0tIEp3VUp5eWZiVERnVmxLOThCTkZw
            dFNnY3ZJMGNrODl6c3dScXE2bFhzMVkKU1SoROS8wW57W/mpkdRMFjmFA+5x5yga
            3F+BG2/uFzUrZCyIfZZ9F2b4VikpQQTleJqXLAIVhriz3njsDRb+gQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18s8m9u69hk3xdjvz7e0c6jmhql2x8k9p98a9nvdy75a9prw7ryfqdp2mh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVTdyNTFOVjFqOGhiNmpZ
            NlBESWpFUVpvekg3SXo1OUwxRWh4VVJyV0ZzCjB5Yk0rZ1lJaENGMElHQ3l5K1hD
            eisrY3lKdVBQMDF5dkhnS3ZqS0trQWcKLS0tIHJiZjI0Uy9qMnRpaENmRFN1RUIz
            enltV0dXRHB2bWVOK0I1UHNVK2ZJQ00K01PJ7jtDfsCbJlJSF9H8RO0cuZwWKjRf
            cc9IhLoVxOxiBNKm5kRw5qVyJQ3tPVjy5x7M6AxQDPQgqKJd3fETwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T01:42:13Z"
    mac: ENC[AES256_GCM,data:waCtEl4UanxPnyFz5YPo/IiN5pklQz2AS8xqj81Y3VQN4Kp8C+cvKpvrkYKZT+54SQp5ID2lH3pHp6tYWiWfnX6culgzru20KKQlHY6Z5lflR/8HD0IFU9P0N3DPBlT9Zn8VjFUDmDZMEr13CghDEOhECDXFWxqt2F4fhmGxWCY=,iv:JxI+lvUhfn+7pJvRNEOij9L6E5blP5rwbKfFRqFJgeI=,tag:VFwIkoywfQmLgZ7VPgaEdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
