api_key:
    open_router: ENC[AES256_GCM,data:+Z0OFQ5NA9O74ECgP5WTgd0nnVx5ZOp9+B3/Yz0T8Enzi5U3qIL9OF3/bCtfOntq4PsTKkCE8mSZEM+i7KKmy5bFPmsocIJYCw==,iv:043FXeyFXdb+4yQmf4rG6tip/z+xtB5bimjbV5x5aPE=,tag:wEBSjMTuqCZXxAdSbvgfoA==,type:str]
sops:
    age:
        - recipient: age140mwr39uc7jv0c8qmuxu8cjdv2w2ac0ktfz07huyt5naeph3pf2q503uwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNE93MTdJY2p5dllLNDlO
            R3Q1M2pEdXQvRUxaVXJuU1RldU5qVkNCcUJJCmp4OE1ZUmNBWlhpUDFqcmtZSlBn
            THRTREJmMEduZVZYV0hhVjNBV3VtclEKLS0tIC9nRVFqaGlnSE5ZUmI1Qi9IVFBz
            a08ydjV3VWEvY28vYi90MXRXMUJjSGcK4c2A6sFQGUiVsaE+MdDOcCUOfmDxULO+
            n9oYUgpzWEHbndsVs+Rk8QXror51/N6iIVjkSmjI9a0IJO71qR0WAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n93u835nu8nxfetappazpl7ns4h3ys2ehzy624rzs2gp887zff9q96v7e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUE9PRFo4OXFoTUt5bGoz
            QlU5dkVjVDlCaHpkZGcvMlJPTGNKQzU4TFhFCkg2NitJWGU2VnNocEY3Mys4Q1Fh
            U0wwcXkrd0I1YlZqNzVZemRZSXRVZGcKLS0tIGZaem50eWFKWmFhTW5XNFZ2NXNp
            V3U1TFR0SHMxdXUxcm9nZ2lvbFFCem8K0YuBnUad9mP2b59Mc3vovhp5LODI1jNa
            dK+5b0+VbjFd+sVAu87g9Y1bRKYq9tFa1VHH/A2BCGUpLFnM7gOVNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T23:04:48Z"
    mac: ENC[AES256_GCM,data:shBqCpflepyUgsyIO9a+PNqj5jjTQ+zXybKdP1LCFNIZWG64WN4DNaGNatMo7BQMPKNhpb0dRrmrK5RKKQs8P/0VvprTMSB5kSlaQ/OOnnJbzlwXed6tdAEQzCoMi9EKE6dpC+hkqXnYzc+gD0xu0gvfqZFBN+9t+lN6tm1S3x0=,iv:6HlsYk1pIR/xvKBH07C6VVY+PaepxaSj/L7/teGp84s=,tag:Jdo5Ai/QDZdVAwtySYUzqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
