api_key:
    open_router: ENC[AES256_GCM,data:+Z0OFQ5NA9O74ECgP5WTgd0nnVx5ZOp9+B3/Yz0T8Enzi5U3qIL9OF3/bCtfOntq4PsTKkCE8mSZEM+i7KKmy5bFPmsocIJYCw==,iv:043FXeyFXdb+4yQmf4rG6tip/z+xtB5bimjbV5x5aPE=,tag:wEBSjMTuqCZXxAdSbvgfoA==,type:str]
    tavily: ENC[AES256_GCM,data:M/6I2oWpBevQ6oWBuWjB5+BOgtSnvCHLOjohGK+tda4K5nzA7yCBKz0=,iv:gGzyQlp87gm5Bz2b0LSjwzWE2e7/p4b1IYlQGJC+z60=,tag:mFg+MKuONL3SYRI8buU9VA==,type:str]
container_registry:
    gitlab:
        username: ENC[AES256_GCM,data:hNlncEKezSRAvQkZo3yvp1vV6Ym24Oiijojf,iv:YaDuzFC1tEv8ZgzDnM39dyjCuYQ8RtpEYpefLFF+mcc=,tag:Hx2h/aFzR30p/JN8erjJnQ==,type:str]
        token: ENC[AES256_GCM,data:zomtF/lG9Mh4mpOyRRxJfWMYc6zJsZpIzA==,iv:WSypFouHyE1sv0LpCd6pCAMoNxIajAKtBmyzetZu7cE=,tag:o96JqeJdA1bBRwxHVP0HDw==,type:str]
sops:
    age:
        - recipient: age140mwr39uc7jv0c8qmuxu8cjdv2w2ac0ktfz07huyt5naeph3pf2q503uwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNE93MTdJY2p5dllLNDlO
            R3Q1M2pEdXQvRUxaVXJuU1RldU5qVkNCcUJJCmp4OE1ZUmNBWlhpUDFqcmtZSlBn
            THRTREJmMEduZVZYV0hhVjNBV3VtclEKLS0tIC9nRVFqaGlnSE5ZUmI1Qi9IVFBz
            a08ydjV3VWEvY28vYi90MXRXMUJjSGcK4c2A6sFQGUiVsaE+MdDOcCUOfmDxULO+
            n9oYUgpzWEHbndsVs+Rk8QXror51/N6iIVjkSmjI9a0IJO71qR0WAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n93u835nu8nxfetappazpl7ns4h3ys2ehzy624rzs2gp887zff9q96v7e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUE9PRFo4OXFoTUt5bGoz
            QlU5dkVjVDlCaHpkZGcvMlJPTGNKQzU4TFhFCkg2NitJWGU2VnNocEY3Mys4Q1Fh
            U0wwcXkrd0I1YlZqNzVZemRZSXRVZGcKLS0tIGZaem50eWFKWmFhTW5XNFZ2NXNp
            V3U1TFR0SHMxdXUxcm9nZ2lvbFFCem8K0YuBnUad9mP2b59Mc3vovhp5LODI1jNa
            dK+5b0+VbjFd+sVAu87g9Y1bRKYq9tFa1VHH/A2BCGUpLFnM7gOVNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T15:34:51Z"
    mac: ENC[AES256_GCM,data:NZW9ZXJ4IgIfusLuKSr17XAgDtrpz7P8JNUPN0qDDuYkJJNGkR+EmpL7rwKTe60e3CdKkMaDBjqJEvU6Se8PXtAixdbRPzdV6WZ5JaI8ACjVHwavkLThToNebPtWc8/knin3z8OewyYSH7MjOLtUEZUI9HAtu9Km7UQHsxCDBxU=,iv:YbOFDESsX149jpmusKxcQEIcllcG5APfr5ofl4OQVOs=,tag:9SGtNTGIdYcS/Kakeb9BrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
